name: Video Database Auto Update
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: # চাইলে আপনি নিজেও বাটন চেপে আপডেট করতে পারবেন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install yt-dlp

      - name: Run Scraper
        run: python script.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'YouTube-Bot'
          git config --global user.email 'bot@github.com'
          git add data.json
          git commit -m "Auto Update: $(date)" || exit 0
          git push
